AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda layer with langchain
Transform: AWS::Serverless-2016-10-31
Parameters:
  pName:
    Type: String
Resources:
  LayerLangchain:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
        - python3.9
        - python3.10
        - python3.11
      ContentUri: ../tmp/langchain
      LayerName: langchain
      Description: langchain==0.0.306 boto3==1.28.57
    Metadata:
      BuildMethod: python3.11
      BuildArchitecture: x86_64
Outputs:
  outLayerLangchain:
    Value: !Ref LayerLangchain